# Generated by Django 6.0.5 on 2026-06-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='chroma_path',
            new_name='index_path',
        ),
    ]
